# Generated by Django 3.0.4 on 2020-03-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_project_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('R', 'Reading'), ('M', 'Math'), ('W', 'Writing'), ('P', 'Phonics'), ('S', 'Science/Social Studies'), ('SEL', 'Social Emotional Learning')], default='R', max_length=3),
            preserve_default=False,
        ),
    ]
